In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('Consumer Behavior Analytics.csv')
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [9]:
# Dataset Overview
df.info()        # Column types, non-null counts

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [8]:
df.tail()        # Last 5 rows

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,No,32,Venmo,Weekly
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,No,24,Venmo,Quarterly
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,No,24,Venmo,Weekly
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,No,33,Venmo,Quarterly

In [6]:
df.sample(5)     # Random 5 rows

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
1428,1429,20,Male,Blouse,Clothing,97,North Dakota,S,Green,Summer,4.9,No,Express,Yes,Yes,42,PayPal,Quarterly
1677,1678,65,Male,Jeans,Clothing,35,Oregon,L,Silver,Summer,3.3,No,Next Day Air,No,No,41,Debit Card,Weekly
519,520,19,Male,Belt,Accessories,54,Minnesota,L,Blue,Summer,4.4,Yes,2-Day Shipping,Yes,Yes,17,Bank Transfer,Quarterly
451,452,66,Male,Jewelry,Accessories,31,Virginia,M,Pink,Summer,4.3,Yes,Express,Yes,Yes,26,Credit Card,Fortnightly
3591,3592,48,Female,Jacket,Outerwear,89,South Dakota,M,Gold,Winter,3.2,No,2-Day Shipping,No,No,38,Bank Transfer,Quarterly

In [7]:
df.shape         # (rows, columns)

(3900, 18)

In [10]:
df.describe()    # Summary stats for numeric columns

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [25]:
# summary of all columns including categorical
df.describe(include = 'all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [14]:
# Checking Column & Data Types
df.columns            # List of column names

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases'],
      dtype='object')

In [12]:
df.dtypes             # Data types

Customer ID                 int64
Age                         int64
Gender                     object
Item Purchased             object
Category                   object
Purchase Amount (USD)       int64
Location                   object
Size                       object
Color                      object
Season                     object
Review Rating             float64
Subscription Status        object
Shipping Type              object
Discount Applied           object
Promo Code Used            object
Previous Purchases          int64
Payment Method             object
Frequency of Purchases     object
dtype: object

In [13]:
df['Season'].dtype    # Type of a specific column

dtype('O')

In [15]:
# Missing Values
df.isnull().sum()     # Missing count per column

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [16]:
df.isna().mean()      # % of missing values per column

Customer ID               0.000000
Age                       0.000000
Gender                    0.000000
Item Purchased            0.000000
Category                  0.000000
Purchase Amount (USD)     0.000000
Location                  0.000000
Size                      0.000000
Color                     0.000000
Season                    0.000000
Review Rating             0.009487
Subscription Status       0.000000
Shipping Type             0.000000
Discount Applied          0.000000
Promo Code Used           0.000000
Previous Purchases        0.000000
Payment Method            0.000000
Frequency of Purchases    0.000000
dtype: float64

Now, Replaced the missing with mean/ median, mean can be affected by outliers skewing the data distribution, median is robust to outliers hence median is chosen. Overall median replacement could be biased as reviews are offered for various items/ category. So Impute the median review rating within each category separate.

In [27]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [28]:
# Checking for null values again
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [17]:
# Checking Unique Value & Counts
# df['col'].nunique()        # Number of unique values
# df['col'].unique()         # Unique values list
# df['col'].value_counts()   # Frequency of each value

In [19]:
# nique counts for all columns
df.nunique()

Customer ID               3900
Age                         53
Gender                       2
Item Purchased              25
Category                     4
Purchase Amount (USD)       81
Location                    50
Size                         4
Color                       25
Season                       4
Review Rating               26
Subscription Status          2
Shipping Type                6
Discount Applied             2
Promo Code Used              2
Previous Purchases          50
Payment Method               6
Frequency of Purchases       7
dtype: int64

In [21]:
# Value counts
for col in df.columns:
    print(f"\n--- {col} ---")
    print(df[col].value_counts())

--- Customer ID ---
Customer ID
3900    1
1       1
2       1
3       1
4       1
       ..
17      1
16      1
15      1
14      1
13      1
Name: count, Length: 3900, dtype: int64

--- Age ---
Age
69    88
57    87
41    86
25    85
49    84
54    83
27    83
50    83
62    83
32    82
58    81
19    81
42    80
31    79
28    79
43    79
37    77
29    76
46    76
63    75
59    75
68    75
56    74
36    74
52    73
64    73
55    73
51    72
65    72
45    72
40    72
35    72
47    71
66    71
30    71
23    71
53    70
38    70
18    69
26    69
21    69
34    68
39    68
48    68
24    68
70    67
22    66
61    65
60    65
33    63
20    62
67    54
44    51
Name: count, dtype: int64

--- Gender ---
Gender
Male      2652
Female    1248
Name: count, dtype: int64

--- Item Purchased ---
Item Purchased
Blouse        171
Pants         171
Jewelry       171
Shirt         169
Dress         166
Sweater       164
Jacket        163
Coat          161
Sunglasses    161
Belt          161
Sandals       160
Socks         159
Skirt         158
Scarf         157
Shorts        157
Hat           154
Handbag       153
Hoodie        151
Shoes         150
T-shirt       147
Sneakers      145
Boots         144
Backpack      143
Gloves        140
Jeans         124
Name: count, dtype: int64

--- Category ---
Category
Clothing       1737
Accessories    1240
Footwear        599
Outerwear       324
Name: count, dtype: int64

--- Purchase Amount (USD) ---
Purchase Amount (USD)
36    62
32    62
94    62
51    61
90    60
      ..
54    36
49    35
87    35
69    34
61    33
Name: count, Length: 81, dtype: int64

--- Location ---
Location
Montana           96
California        95
Idaho             93
Illinois          92
Alabama           89
Minnesota         88
New York          87
Nevada            87
Nebraska          87
Delaware          86
Maryland          86
Vermont           85
Louisiana         84
North Dakota      83
West Virginia     81
Missouri          81
New Mexico        81
Mississippi       80
Kentucky          79
Arkansas          79
Georgia           79
Indiana           79
Connecticut       78
North Carolina    78
Maine             77
Ohio              77
Virginia          77
Texas             77
Tennessee         77
South Carolina    76
Oklahoma          75
Wisconsin         75
Colorado          75
Oregon            74
Pennsylvania      74
Michigan          73
Washington        73
Alaska            72
Massachusetts     72
Utah              71
Wyoming           71
New Hampshire     71
South Dakota      70
Iowa              69
Florida           68
New Jersey        67
Arizona           65
Hawaii            65
Rhode Island      63
Kansas            63
Name: count, dtype: int64

--- Size ---
Size
M     1755
L     1053
S      663
XL     429
Name: count, dtype: int64

--- Color ---
Color
Olive        177
Yellow       174
Silver       173
Teal         172
Green        169
Black        167
Cyan         166
Violet       166
Gray         159
Maroon       158
Orange       154
Charcoal     153
Pink         153
Blue         152
Magenta      152
Purple       151
Peach        149
Red          148
Beige        147
Indigo       147
Lavender     147
Turquoise    145
White        142
Brown        141
Gold         138
Name: count, dtype: int64

--- Season ---
Season
Spring    999
Fall      975
Winter    971
Summer    955
Name: count, dtype: int64

--- Review Rating ---
Review Rating
3.4    182
4.0    181
4.6    170
4.2    169
2.9    166
3.9    162
3.0    162
4.9    162
2.6    158
4.4    158
3.1    156
2.7    154
3.5    152
3.2    152
3.7    149
4.7    148
4.1    148
4.3    147
3.6    147
3.3    146
4.8    144
3.8    141
4.5    139
2.8    136
5.0     68
2.5     66
Name: count, dtype: int64

--- Subscription Status ---
Subscription Status
No     2847
Yes    1053
Name: count, dtype: int64

--- Shipping Type ---
Shipping Type
Free Shipping     675
Standard          654
Store Pickup      650
Next Day Air      648
Express           646
2-Day Shipping    627
Name: count, dtype: int64

--- Discount Applied ---
Discount Applied
No     2223
Yes    1677
Name: count, dtype: int64

--- Promo Code Used ---
Promo Code Used
No     2223
Yes    1677
Name: count, dtype: int64

--- Previous Purchases ---
Previous Purchases
31    97
21    96
14    92
4     91
3     91
24    91
48    90
47    90
5     87
6     87
18    84
20    83
1     83
42    83
45    83
33    82
11    82
40    82
30    82
39    81
32    81
28    80
12    79
25    79
34    79
27    78
19    78
37    78
46    78
50    77
26    77
10    76
15    73
23    73
2     72
44    72
36    71
16    70
38    70
41    70
13    69
29    69
8     67
17    67
9     65
22    65
7     65
43    64
35    63
49    58
Name: count, dtype: int64

--- Payment Method ---
Payment Method
PayPal           677
Credit Card      671
Cash             670
Debit Card       636
Venmo            634
Bank Transfer    612
Name: count, dtype: int64

--- Frequency of Purchases ---
Frequency of Purchases
Every 3 Months    584
Annually          572
Quarterly         563
Monthly           553
Bi-Weekly         547
Fortnightly       542
Weekly            539
Name: count, dtype: int64

In [22]:
# Unique values for all columns
for col in df.columns:
    print(f"\nUnique values in {col}:")
    print(df[col].unique())

Unique values in Customer ID:
[   1    2    3 ... 3898 3899 3900]

Unique values in Age:
[55 19 50 21 45 46 63 27 26 57 53 30 61 65 64 25 52 66 31 56 18 38 54 33
 36 35 29 70 69 67 20 39 42 68 49 59 47 40 41 48 22 24 44 37 58 32 62 51
 28 43 34 23 60]

Unique values in Gender:
['Male' 'Female']

Unique values in Item Purchased:
['Blouse' 'Sweater' 'Jeans' 'Sandals' 'Sneakers' 'Shirt' 'Shorts' 'Coat'
 'Handbag' 'Shoes' 'Dress' 'Skirt' 'Sunglasses' 'Pants' 'Jacket' 'Hoodie'
 'Jewelry' 'T-shirt' 'Scarf' 'Hat' 'Socks' 'Backpack' 'Belt' 'Boots'
 'Gloves']

Unique values in Category:
['Clothing' 'Footwear' 'Outerwear' 'Accessories']

Unique values in Purchase Amount (USD):
[ 53  64  73  90  49  20  85  34  97  31  68  72  51  81  36  38  48  62
  37  88  22  25  56  94  79  67  91  33  69  45  60  76  39 100  21  43
  54  55  30  28  59  24  83  46  70  29  26  58  96  40  32  95  41  47
  99  87  92  98  89  35  75  65  86  84  77  27  23  74  80  42  61  82
  78  93  50  57  66  44  52  71  63]

Unique values in Location:
['Kentucky' 'Maine' 'Massachusetts' 'Rhode Island' 'Oregon' 'Wyoming'
 'Montana' 'Louisiana' 'West Virginia' 'Missouri' 'Arkansas' 'Hawaii'
 'Delaware' 'New Hampshire' 'New York' 'Alabama' 'Mississippi'
 'North Carolina' 'California' 'Oklahoma' 'Florida' 'Texas' 'Nevada'
 'Kansas' 'Colorado' 'North Dakota' 'Illinois' 'Indiana' 'Arizona'
 'Alaska' 'Tennessee' 'Ohio' 'New Jersey' 'Maryland' 'Vermont'
 'New Mexico' 'South Carolina' 'Idaho' 'Pennsylvania' 'Connecticut' 'Utah'
 'Virginia' 'Georgia' 'Nebraska' 'Iowa' 'South Dakota' 'Minnesota'
 'Washington' 'Wisconsin' 'Michigan']

Unique values in Size:
['L' 'S' 'M' 'XL']

Unique values in Color:
['Gray' 'Maroon' 'Turquoise' 'White' 'Charcoal' 'Silver' 'Pink' 'Purple'
 'Olive' 'Gold' 'Violet' 'Teal' 'Lavender' 'Black' 'Green' 'Peach' 'Red'
 'Cyan' 'Brown' 'Beige' 'Orange' 'Indigo' 'Yellow' 'Magenta' 'Blue']

Unique values in Season:
['Winter' 'Spring' 'Summer' 'Fall']

Unique values in Review Rating:
[3.1 3.5 2.7 2.9 3.2 2.6 4.8 4.1 4.9 4.5 4.7 2.8 4.6 3.3 4.4 3.6 5.  4.
 nan 4.2 3.7 3.9 3.  3.8 3.4 4.3 2.5]

Unique values in Subscription Status:
['Yes' 'No']

Unique values in Shipping Type:
['Express' 'Free Shipping' 'Next Day Air' 'Standard' '2-Day Shipping'
 'Store Pickup']

Unique values in Discount Applied:
['Yes' 'No']

Unique values in Promo Code Used:
['Yes' 'No']

Unique values in Previous Purchases:
[14  2 23 49 31 19  8  4 26 10 37 34 44 36 17 46 50 22 32 40 16 13  7 41
 45 38 48 18 15 25 39 35 29 21 43  3  5 24 42 47 28 20 33  1  9 12 27 11
 30  6]

Unique values in Payment Method:
['Venmo' 'Cash' 'Credit Card' 'PayPal' 'Bank Transfer' 'Debit Card']

Unique values in Frequency of Purchases:
['Fortnightly' 'Weekly' 'Annually' 'Quarterly' 'Bi-Weekly' 'Monthly'
 'Every 3 Months']

In [24]:
# Summary of all columns
df.agg(['nunique', 'dtype']).T

                       nunique    dtype
Customer ID               3900    int64
Age                         53    int64
Gender                       2   object
Item Purchased              25   object
Category                     4   object
Purchase Amount (USD)       81    int64
Location                    50   object
Size                         4   object
Color                       25   object
Season                       4   object
Review Rating               26  float64
Subscription Status          2   object
Shipping Type                6   object
Discount Applied             2   object
Promo Code Used              2   object
Previous Purchases          50    int64
Payment Method               6   object
Frequency of Purchases       7   object

In [29]:
# column name with snake casing, lower case & underscore for code readability and use amongst platforms
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')

In [30]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [32]:
df = df.rename(columns ={"purchase_amount_(usd)" : "purchase_amount"})
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [ ]:
# feature engineering, create a column for age_group
labels = ['Youth', 'Adult', 'Mature', 'Senior']
df['age_group'] = pd.qcut(df['age'], q = 4, labels = labels)

- pd.qcut() divides a column into equal-sized groups (quantiles)

q = 4 means:
→ split the age column into 4 groups, each containing 25% of the data.

So instead of dividing by fixed age ranges (like 18–25), it divides based on the distribution of your data.

In [36]:
# age_group is a new column showing which age quantile each person belongs to
df[['age', 'age_group']].head(10)

   age age_group
0   55    Mature
1   19     Youth
2   50    Mature
3   21     Youth
4   45    Mature
5   46    Mature
6   63    Senior
7   27     Youth
8   26     Youth
9   57    Mature

In [48]:
# creating purchase frequency days column
# unique() all the distinct values in a column, to Understand categories
df['frequency_of_purchases'].unique()

array(['Fortnightly', 'Weekly', 'Annually', 'Quarterly', 'Bi-Weekly',
       'Monthly', 'Every 3 Months'], dtype=object)

In [46]:
# nunique() Returns the count of unique values, to Check cardinality
df['frequency_of_purchases'].nunique()

7

In [49]:
# value_counts() how many times each appears to understand the frequency distribution
df['frequency_of_purchases'].value_counts()

frequency_of_purchases
Every 3 Months    584
Annually          572
Quarterly         563
Monthly           553
Bi-Weekly         547
Fortnightly       542
Weekly            539
Name: count, dtype: int64

In [55]:
# creating purchase_frequency_days column
# textual frequencies to number for quicker analysis
frequency_mapping = {
    'Every 3 Months':    90,
'Annually'    :    365,
'Quarterly'     :   90,
'Monthly'     :  30,
'Bi-Weekly'      : 14,
'Fortnightly'      :14,
'Weekly'      :     7 }
df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [56]:
df[['purchase_frequency_days', 'frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

In [57]:
df[['discount_applied', 'promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [60]:
# compares both columns row by row 
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [61]:
# they are of same info so we dont need promo_code_used column
df = df.drop('promo_code_used', axis = 1)

In [62]:
# check for columns
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [64]:
df.shape

(3900, 19)

In [66]:
# connecting jupyter notebook to postgresql to load data
!pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\users\jesee\appdata\local\programs\python\python312\lib\site-packages (2.9.10)
Requirement already satisfied: sqlalchemy in c:\users\jesee\appdata\local\programs\python\python312\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\users\jesee\appdata\local\programs\python\python312\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\jesee\appdata\local\programs\python\python312\lib\site-packages (from sqlalchemy) (4.14.0)

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [74]:
from sqlalchemy import create_engine, text
import pandas as pd

# engine with db_name 
engine = create_engine("postgresql+psycopg2://postgres:1234@localhost:5432/Customer_Behavior_Analytics")

# Testing connection
with engine.connect() as conn:
    result = conn.execute(text("SELECT version();"))
    print(result.fetchone())

# Step 2: Load DataFrame into PostgreSQL
table_name = "customer" # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)
print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

('PostgreSQL 17.0 on x86_64-windows, compiled by msvc-19.41.34120, 64-bit',)
Data successfully loaded into table 'customer' in database 'Customer_Behavior_Analytics'.

In [ ]:
# mysql !pip install pymysql sqlalchemy

In [75]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')